version: 2.1

orbs:
  python: circleci/python@1.4.0

workflows:
  check:
    jobs: &jobs
      - black
      - mypy
      - pylint
      - pytest

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs: *jobs

commands:
  install:
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: test-requirements.txt
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install module itself
          command: pip install .

jobs:
  black:
    docker:
      - image: cimg/python:3.8
    steps:
      - install
      - run:
          name: Run black
          command: black --verbose --check

  mypy:
    docker:
      - image: cimg/python:3.8
    steps:
      - install
      - run:
          name: Run mypy
          command: mypy --verbose --pretty bmw_cardata

  pylint:
    docker:
      - image: cimg/python:3.8
    steps:
      - install
      - run:
          name: Run pylint
          command: pylint --verbose bmw_cardata

  pytest:
    docker:
      - image: cimg/python:3.8
    steps:
      - install
      - run:
          name: Run pylint
          command: pytest
